config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :grannies do
    resources :bookings, only: [ :new, :create ]
  end
  resources :bookings, only: [:index, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :granny, class_name: "User", foreign_key: "granny_id"
  validates :start_date, :end_date, presence: true
end

app/models/granny_skill.rb
class GrannySkill < ApplicationRecord
  belongs_to :user
  has_many :skills
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :granny_skill
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch::Model
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :user_bookings, :class_name => 'Booking', :foreign_key => 'user_id', dependent: :destroy
  has_many :granny_bookings, :class_name => 'Booking', :foreign_key => 'granny_id', dependent: :destroy
  has_one_attached :photo

  validates :first_name, :last_name, :birth_date, :location, presence: true

  validates :description, :price, presence: true, if: :granny?

  scope :grannies, -> { where(granny: true) }

  pg_search_scope :search_by_name_and_description,
    against: [ :first_name, :last_name, :description, :location ],
    using: {
      tsearch: { prefix: true }
    }

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birth_date, :description, :granny, :location, :price, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :birth_date, :description, :granny, :location, :price])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user: current_user)
  end

  def new
    @booking = Booking.new
    @granny = User.find(params[:granny_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @granny = User.find(params[:granny_id])
    @booking.granny = @granny
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/grannies_controller.rb
class GranniesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # uses scope `grannies` in user.rb
    if params[:query].present?
      @grannies = User.grannies.search_by_name_and_description(params[:query])
    else
      @grannies = User.grannies
    end
  end

  def show
    @granny = User.grannies.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home;end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h2 class="text-center">GrannyMonster Lover Profile</h2>
<h3 >MY BOOKINGS</h3>
<div class="containerbook">
<div class='booking-card'>
<%@bookings.each do |booking| %>
  <div class='booking-div'>
    <p><%= "From: #{booking.start_date} To: #{booking.end_date}"%></p>
    <p><%=booking.granny.description %></p>
    <p> With <%= booking.granny.name %></p>

    <%= link_to 'Delete booking', booking, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-all" %>
   </div>
  </div>
  <%end %>
</div>
</div>

app/views/bookings/new.html.erb
<div class="background" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://res.cloudinary.com/monstergrannies/image/upload/v1653511008/Grannies/banner2_lyoots.jpg);">

<div class='container mt-5'>
  <h2 class="text-center">BOOK YOUR GRANDMONSTER</h2>

    <div class='granny-card d-flex'>
      <div class="col-4 d-flex" >
        <%= cl_image_tag @granny.photo.key, width: 300 %>
      </div>
      <div class="col-8">
        <div class='card-details '>
          <h2><%= "#{@granny.first_name} #{@granny.last_name}" %></h2>
          <h3 class="py-2"><%= @granny.description%></h3>
          <div class="d-flex justify-content-between">
          <h3><%= @granny.location%></h3>
          </div>
          <div class="d-flex justify-content-between">
          <h3><%= (Date.today - @granny.birth_date).to_i / 365 %> years young</h3>
          </div>
          <div class="d-flex justify-content-between">
          <h3> <strong> <%= @granny.price%> € </strong></h3>
        </div>
        <div class="d-flex justify-content-between mt-3">
          <%= link_to "Book this grandmonster", new_granny_booking_path(@granny), class: "btn-all" %>
          <%= link_to "Back for more fabulosity", grannies_path, class: "btn-all" %>
        </div>
        <%= simple_form_for [@granny, @booking],url:granny_bookings_path(@granny) do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/grannies/index.html.erb
<div class="container mt-5">
  <div class="row">
    <%@grannies.each do |granny| %>
      <div class="col-4">
        <div class='card mb-3'>
          <div class="card-body card-results card-select">
            <%= link_to granny_path(granny) do %>
              <%= cl_image_tag granny.photo.key %>
              <h2><%= "#{granny.first_name} #{granny.last_name}" %></h2>
              <p><%= granny.description %></p>
              <div class="d-flex justify-content-between">
                <p><%= granny.location%></p>
                <p><%= (Date.today - granny.birth_date).to_i / 365 %> years young</p>
              </div>
            <%end %>
            <div class="d-flex justify-content-between mt-2">
              <p><%= link_to "Book", new_granny_booking_path(granny), class: "btn-all book-link" %></p>
              <p> <strong> €<%= granny.price%> </strong></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/grannies/show.html.erb
<div class='container mt-5'>
  <h1>The chosen Grandmonster</h1>
  <div class='granny-card d-flex'>
    <div class="col-4 d-flex justify-content-center old" >
      <%= cl_image_tag @granny.photo.key, width: 300 %>
    </div>
    <div class="col-8">
      <div class='card-details '>
        <h2><%= "#{@granny.first_name} #{@granny.last_name}" %></h2>
        <h3 class="py-2"><%= @granny.description%></h3>
        <div class="d-flex justify-content-between">
        <h3><%= @granny.location%></h3>
        </div>
        <div class="d-flex justify-content-between">
        <h3><%= (Date.today - @granny.birth_date).to_i / 365 %> years young</h3>
        </div>
        <div class="d-flex justify-content-between">
        <h3> <strong> <%= @granny.price%> € </strong></h3>
      </div>
      <div class="d-flex justify-content-between mt-3">
        <%= link_to "Book this grandmonster", new_granny_booking_path(@granny), class: "btn-all" %>
        <%= link_to "Back for more fabulosity", grannies_path, class: "btn-all" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonsterGrannies</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;900&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag image_url("https://res.cloudinary.com/monstergrannies/image/upload/v1653563963/Grannies/logorosa_tughri.png") %>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<body>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://res.cloudinary.com/monstergrannies/image/upload/v1653510921/Grannies/banner_nv4nb1.jpg);">

    <div class="container">
      <h1>GRANNYUP YOUR LIFE!</h1>
      <%= link_to "SEE ALL", grannies_path, class: "btn-all" %>
    </div>
  </div>

<div class="skills-round">

  <div class="card-category " style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://res.cloudinary.com/monstergrannies/image/upload/v1653554440/Grannies/Prancheta_1_1-20_lko3fv.jpg)">
   <p>CLUBBING</p>
  </div>

  <div class="card-category " style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://res.cloudinary.com/monstergrannies/image/upload/c_scale,h_230/v1653602135/Grannies/Prancheta_1_2-20_plbm5u.jpg)">
   <p>TALK TO</p>
  </div>

  <div class="card-category " style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://res.cloudinary.com/monstergrannies/image/upload/v1653554440/Grannies/Prancheta_1-20_efkut9.jpg)">
    <p>COOKING</p>
  </div>
</div>

<div class="banner2" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://res.cloudinary.com/monstergrannies/image/upload/v1653511008/Grannies/banner2_lyoots.jpg);">

    <div class="container">
      <h1>ADD YOUR CRAZY SKILLS!</h1>
      <a class="btn-all2" href="#">JOIN OUR GRANNYMONSTER SQUAD</a>
     </div>
  </div>




</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-envelope"></i></a>
  </div>
  <div class="footer-copyright">
    © 2022 MonsterGrannies
  </div>
</footer>

app/views/shared/_navbar.html.erb
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <img src="https://res.cloudinary.com/monstergrannies/image/upload/v1653563963/Grannies/logorosa_tughri.png" />
      <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="teste ">
      <%= form_tag grannies_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "js-search",
          placeholder: "Search..."%>
        <%#= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
      <%# <input placeholder='Search...' class='js-search' type="text"> %>
          <i class="fa fa-search"></i>
    </div>

  <div class="menu">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Grannies", grannies_path, class: "nav-link" %>
          </li>

          <li class="nav-item active">
              <%= link_to "Add a grannie", grannies_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/monstergrannies/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1653661829/users%20photos/220504_Le_Wagon_116-X2_afodb1.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Granny Lover Profile", bookings_path, class: "dropdown-item" %>
              <%= link_to "Edit your account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item"-->
            <li class="nav-item active">
              <%= link_to "Grannies", grannies_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Add a grannie", grannies_path, class: "nav-link" %>
            </li>
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              <%= link_to "SignUp", new_user_registration_path, class: "nav-link" %>
          </li-->
        <% end %>
      </ul>
    </div>
    </div>
  </div>
</div>